
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.deDE = {
  COULD_NOT_DETERMINE_POSITION = [[Aktuelle Position konnte nicht ermittelt werden]],
  NO_WAYPOINTS_MATCH = [[Keine Wegpunkte entsprechen deiner Suche.]],
  CLICK_TO_HIGHLIGHT = [[Klicken zum Markieren]],
  FONT = [[%1$s Schriftart]],
  NEW_WAYPOINT = [[Neuer Wegpunkt]],
  CANNOT_SET_WAYPOINT = [[Wegpunkt für diesen Ort kann nicht gesetzt werden (Karte %s, %s).]],
  OVERRIDE_WAYPOINT_BG = [[Textur wählen]],
  SETTINGS_TOMTOM_READY = [[TomTom ist geladen und bereit.]],
  NO_DESCRIPTION = [[Keine Beschreibung]],
  WAYPOINT_IN = [[Wegpunkt in %s]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[Stufen:
1 - Elternteil
2 - Kontinent
3 - Welt]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[Klicken Sie hier, um diesen Wegpunkt zu aktivieren]],
  MAP_PINS = [[Map Pins]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[Titelschrift]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[Standardmäßige Karten-Pin-Ebene]],
  SLASH_TT2 = [[Aktuelle Position speichern]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[Standard-Karten-Pin-Größe]],
  NO_SAVED_WAYPOINTS_YET = [[Noch keine gespeicherten Wegpunkte.]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[Schriftgröße des Titels]],
  WAYPOINT_NAME_COLOR = [[Farbe des Wegpunktnamens]],
  FONT_OPTIONS = [[Schrift]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom ist installiert und wird bei Bedarf geladen.]],
  DELETE_ALL_SAVED_WAYPOINTS = [[Alle gespeicherten Wegpunkte in Ihrer Sammlung löschen]],
  SETTINGS_NAVIGATION_HINT = [[Wenn aktiviert, wird TomTom bevorzugt. Der Spielkarten-Pin wird anderweitig verwendet, auch wenn TomTom ausfällt.]],
  SETTINGS_USE_TOMTOM = [[Verwenden Sie TomTom mit %s]],
  CLICK_TO_SAVE = [[Klicken Sie hier, um diesen Speicherort in Ihrer Sammlung zu speichern]],
  WAYPOINTS = [[Wegpunkte]],
  PROFILE_LOADED = [[Profil erfolgreich geladen]],
  RIGHT_CLICK_FOR_OPTIONS = [[Rechtsklick für weitere Optionen]],
  COORDINATES = [[Koordinaten]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[Klicken Sie hier, um diesen Wegpunkt zu deaktivieren]],
  LOADED = [[geladen.]],
  DELETE_WAYPOINT_DESC = [[Diesen Wegpunkt aus deiner Sammlung entfernen.]],
  LEFT_CLICK_TOGGLE = [[Linksklick: UI ein-/ausblenden]],
  WAYPOINT = [[Wegpunkt]],
  SLASH_TT1 = [[Öffnen/Schließen %s]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[Persistente Karten-Pins]],
  COULD_NOT_PARSE_COORDS = [[Koordinaten konnten nicht analysiert werden]],
  MORE_OPTIONS = [[(weitere Optionen in -> %s -> %s ->
 %s -> %s)]],
  SLASH_COMMANDS = [[Slash-Befehle]],
  DELETE_ALL = [[Alle löschen]],
  SLASH_TT3 = [[Verwendung: %s #mapId x y name -d description]],
  TEXTURES = [[Texturen]], -- (new Python translation)
  WAYPOINT_NAME_COLOR_RESET = [[Rechtsklick: auf die Standardschriftfarbe zurücksetzen.]],
  CHAT_WAYPOINT = [[Zum Chat senden]],
  SETTINGS_TOMTOM_MISSING = [[TomTom ist nicht installiert.]],
  EDIT_WAYPOINT_DESC = [[Name und Beschreibung dieses Wegpunkts aktualisieren.]],
  WAYPOINT_VIA_TOMTOM = [[(TomTom)]],
  NO_SAVED_WAYPOINT = [[Kein gespeicherter Wegpunkt mit dieser ID]],
  SETTINGS_NAVIGATION = [[Navigation]],
  CONFIRM_DELETE_ALL = [[Sind Sie sicher, dass Sie löschen möchten? Das kann nicht rückgängig gemacht werden]],
  CTRL_C_COPY = [[Strg + C zum Kopieren des markierten Textes.]],
  WAYPOINT_SET_TO = [[Wegpunkt festgelegt auf %s]],
  NO_WAYPOINT_TO_CHAT = [[Kein Wegpunkt zum Teilen]],
  INVALID_COORDS = [[Ungültige Koordinaten: %s (muss zwischen 0-100 liegen)]],
}
