
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.esES = {
  COULD_NOT_DETERMINE_POSITION = [[No se pudo determinar la posición actual]],
  NO_WAYPOINTS_MATCH = [[Ningún punto de ruta coincide con tu búsqueda.]],
  CLICK_TO_HIGHLIGHT = [[Clic para resaltar]],
  FONT = [[Fuente]],
  NEW_WAYPOINT = [[Nuevo punto de paso]],
  CANNOT_SET_WAYPOINT = [[No se puede establecer un punto de ruta para esta ubicación (mapa %s, %s).]],
  OVERRIDE_WAYPOINT_BG = [[Elegir textura]],
  SETTINGS_TOMTOM_READY = [[TomTom está cargado y listo.]],
  NO_DESCRIPTION = [[Sin descripción]],
  WAYPOINT_IN = [[Waypoint en %s]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[Niveles:
1 - Padre
2 - Continente
3 - Mundo]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[Haga clic para activar este waypoint]],
  MAP_PINS = [[Pines del Mapa]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[Fuente del Título]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[Nivel de pin de mapa predeterminado]],
  SLASH_TT2 = [[Actualmente]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[Tamaño predeterminado del pin del mapa]],
  NO_SAVED_WAYPOINTS_YET = [[Aún no hay puntos de ruta guardados.]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[Altura de la línea de la fuente del título]],
  WAYPOINT_NAME_COLOR = [[Color del nombre del waypoint]],
  FONT_OPTIONS = [[Opciones de fuentes]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom está instalado y se cargará cuando sea necesario.]],
  DELETE_ALL_SAVED_WAYPOINTS = [[Elimina todos los waypoints guardados en tu colección]],
  SETTINGS_NAVIGATION_HINT = [[Cuando está habilitado, se prefiere TomTom. El PIN del mapa del juego se utiliza de otra manera, incluso cuando TomTom falla.]],
  SETTINGS_USE_TOMTOM = [[Usar TomTom con %s]],
  CLICK_TO_SAVE = [[Haz clic para guardar esta ubicación en tu colección]],
  WAYPOINTS = [[Waypoints]],
  PROFILE_LOADED = [[Perfil cargado correctamente]],
  RIGHT_CLICK_FOR_OPTIONS = [[Opciones de menú contextual]],
  COORDINATES = [[Coordenadas]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[Haga clic para desactivar este waypoint]],
  LOADED = [[cargado.]],
  DELETE_WAYPOINT_DESC = [[Eliminar este punto de ruta de tu colección.]],
  LEFT_CLICK_TOGGLE = [[Clic izquierdo: Alternar interfaz]],
  WAYPOINT = [[Punto de ruta]],
  SLASH_TT1 = [[Abrir/cerrar %s]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[Pines de mapa persistentes]],
  COULD_NOT_PARSE_COORDS = [[Imposible interpretar las coordenadas.]],
  MORE_OPTIONS = [[(más opciones en -> %s -> %s ->
 %s -> %s)]],
  SLASH_COMMANDS = [[Comandos de barra oblicua]],
  DELETE_ALL = [[Eliminar todo]],
  SLASH_TT3 = [[Uso: %s #mapId x y name -d description]],
  TEXTURES = [[Texturas]], -- (new Python translation)
  WAYPOINT_NAME_COLOR_RESET = [[Haga clic con el botón derecho del ratón: restablezca el color de fuente predeterminado.]],
  CHAT_WAYPOINT = [[- Enviar al chat]],
  SETTINGS_TOMTOM_MISSING = [[TomTom no está instalado.]],
  EDIT_WAYPOINT_DESC = [[Actualizar el nombre y la descripción de este punto de ruta.]],
  WAYPOINT_VIA_TOMTOM = [[(TomTom)]],
  NO_SAVED_WAYPOINT = [[No hay punto de ruta guardado con ese ID]],
  SETTINGS_NAVIGATION = [[Navegación]],
  CONFIRM_DELETE_ALL = [[¿Estás seguro de que deseas eliminar todas las variaciones? Esto no se puede deshacer.]],
  CTRL_C_COPY = [[Ctrl + C para copiar el texto resaltado.]],
  WAYPOINT_SET_TO = [[Waypoint establecido en %s]],
  NO_WAYPOINT_TO_CHAT = [[No hay punto de ruta para compartir]],
  INVALID_COORDS = [[Coordenadas no válidas: %s (debe estar entre 0-100)]],
}
