
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.frFR = {
  SLASH_TT3 = [[Utilisation : %s #mapId x y name -d description]],
  SETTINGS_USE_TOMTOM = [[Utiliser TomTom avec %s]],
  NO_WAYPOINTS_MATCH = [[Aucun point de repère ne correspond à votre recherche.]],
  COULD_NOT_DETERMINE_POSITION = [[Impossible de déterminer la position actuelle]],
  NO_DESCRIPTION = [[Aucune description]],
  WAYPOINT = [[Point de repère]],
  COORDINATES = [[Coordonnées]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[Niveaux :
1 - Parent
2 - Continent
3 - Monde]],
  WAYPOINT_SET_TO = [[Point de cheminement défini sur %s]],
  WAYPOINT_VIA_TOMTOM = [[Tom-Tom]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[Cliquez pour désactiver ce point de cheminement]],
  FONT = [[Police]],
  INVALID_COORDS = [[Coordonnées non valides : %s (doit être compris entre 0 et 100)]],
  DELETE_ALL_SAVED_WAYPOINTS = [[Supprimer tous les points de cheminement enregistrés dans votre collection]],
  WAYPOINT_NAME_COLOR = [[Couleur du nom du point de cheminement]],
  CLICK_TO_HIGHLIGHT = [[Cliquer pour surligner]],
  MAP_PINS = [[Épingles de carte]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[Niveau d'épingle de la carte par défaut]],
  DELETE_WAYPOINT_DESC = [[Supprimer ce point de repère de votre collection.]],
  SETTINGS_NAVIGATION_HINT = [[Lorsque cette option est activée, TomTom est préférable. Le code PIN de la carte du jeu est utilisé autrement, y compris lorsque TomTom échoue.]],
  SETTINGS_NAVIGATION = [[Navigation]],
  NO_SAVED_WAYPOINTS_YET = [[Aucun point de repère sauvegardé pour le moment.]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[Cliquez pour activer ce point de cheminement]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[Hauteur de la police du titre]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[Titre Police]],
  SLASH_TT2 = [[Enregistrer position actuelle]],
  WAYPOINT_NAME_COLOR_RESET = [[Clic droit : réinitialiser à la couleur de police par défaut.]],
  FONT_OPTIONS = [[Options de police]],
  CONFIRM_DELETE_ALL = [[Êtes-vous sûr de vouloir supprimer? L'annulation est impossible]],
  SETTINGS_TOMTOM_READY = [[TomTom est chargé et prêt.]],
  SETTINGS_TOMTOM_MISSING = [[TomTom n'est pas installé.]],
  NEW_WAYPOINT = [[Nouveau Point de cheminement]],
  SLASH_TT1 = [[Ouvrir/fermer %s]],
  COULD_NOT_PARSE_COORDS = [[Impossible d&apos;analyser les coordonnées.]],
  PROFILE_LOADED = [[Profil chargé avec succès]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom est installé et se charge en cas de besoin.]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[Épingles de carte persistantes]],
  OVERRIDE_WAYPOINT_BG = [[Choisir une texture]],
  WAYPOINT_IN = [[Point de cheminement dans %s]],
  LEFT_CLICK_TOGGLE = [[Clic gauche : Afficher/Masquer l'interface]],
  SLASH_COMMANDS = [[Commandes de barre oblique]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[Taille d'épingle de carte par défaut]],
  EDIT_WAYPOINT_DESC = [[Mettre à jour le nom et la description de ce point de repère.]],
  PIN_TEXTURES = [[Style de l'épingle]], -- (new Python translation)
  NO_WAYPOINT_TO_CHAT = [[Aucun point de repère à partager]],
  TEXTURES = [[Textures]],
  RIGHT_CLICK_FOR_OPTIONS = [[ - Clic droit pour les options]],
  CHAT_WAYPOINT = [[Envoyer au chat]],
  CTRL_C_COPY = [[Ctrl + C pour copier le texte surligné.]],
  CANNOT_SET_WAYPOINT = [[Impossible de définir un point de repère pour cet emplacement (carte %s, %s).]],
  NO_SAVED_WAYPOINT = [[Aucun point de repère sauvegardé avec cet identifiant]],
  DELETE_ALL = [[Tout supprimer]],
  MORE_OPTIONS = [[(plus d'options dans -> %s -> %s ->
 %s -> %s)]],
  LOADED = [[chargé]],
  CLICK_TO_SAVE = [[Cliquez pour enregistrer cet emplacement dans votre collection]],
  WAYPOINTS = [[Point de passage]],
}
