
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.koKR = {
  SLASH_TT3 = [[사용법: %s # mapId x y name -d description]],
  SETTINGS_USE_TOMTOM = [[%s과 함께 TomTom을 사용합니다]],
  NO_WAYPOINTS_MATCH = [[검색과 일치하는 경유지가 없습니다.]],
  COULD_NOT_DETERMINE_POSITION = [[현재 위치를 확인할 수 없습니다]],
  NO_DESCRIPTION = [[설명 없음]],
  WAYPOINT = [[경유지]],
  COORDINATES = [[좌표]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[레벨:
1 - 부모
2 - 대륙
3 - 세계]],
  WAYPOINT_SET_TO = [[웨이포인트를 %s (으) 로 설정]],
  WAYPOINT_VIA_TOMTOM = [[(TomTom)]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[이 웨이포인트를 비활성화하려면 클릭하세요]],
  FONT = [[폰트]],
  INVALID_COORDS = [[유효하지 않은 좌표: %s (0-100 사이여야 함)]],
  DELETE_ALL_SAVED_WAYPOINTS = [[컬렉션에 저장된 모든 웨이포인트 삭제]],
  WAYPOINT_NAME_COLOR = [[중간 지점 이름 색상]],
  CLICK_TO_HIGHLIGHT = [[클릭하여 강조 표시]],
  MAP_PINS = [[지도 핀]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[기본 지도 핀 레벨]],
  DELETE_WAYPOINT_DESC = [[컬렉션에서 이 경유지를 제거합니다.]],
  SETTINGS_NAVIGATION_HINT = [[활성화되면 TomTom이 선호됩니다. TomTom이 실패한 경우를 포함하여 게임 맵 핀이 사용됩니다.]],
  SETTINGS_NAVIGATION = [[탐색]],
  NO_SAVED_WAYPOINTS_YET = [[아직 저장된 경유지가 없습니다.]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[이 웨이포인트를 활성화하려면 클릭하세요]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[타이틀 폰트 높이]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[타이틀 폰트]],
  SLASH_TT2 = [[현재 위치]],
  WAYPOINT_NAME_COLOR_RESET = [[마우스 오른쪽 버튼 클릭: 기본 글꼴 색상으로 재설정합니다.]],
  FONT_OPTIONS = [[폰트]],
  CONFIRM_DELETE_ALL = [[전체 옵션을 제거하시겠습니까? 복구할 수 없습니다.]],
  SETTINGS_TOMTOM_READY = [[TomTom이 로드되어 준비되었습니다.]],
  SETTINGS_TOMTOM_MISSING = [[TomTom이 설치되지 않았습니다.]],
  NEW_WAYPOINT = [[새로운 웨이포인트]],
  SLASH_TT1 = [[%s 열기/닫기]],
  COULD_NOT_PARSE_COORDS = [[좌표를 분석할 수 없습니다.]],
  PROFILE_LOADED = [[프로필이 성공적으로 로드되었습니다]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom이 설치되어 있으며 필요할 때 로드됩니다.]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[영구 맵 핀]],
  OVERRIDE_WAYPOINT_BG = [[텍스처 선택]],
  WAYPOINT_IN = [[%s 의 웨이포인트]],
  LEFT_CLICK_TOGGLE = [[좌클릭: UI 전환]],
  SLASH_COMMANDS = [[슬래시 명령]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[기본 지도 핀 크기]],
  EDIT_WAYPOINT_DESC = [[이 경유지의 이름과 설명을 업데이트합니다.]],
  PIN_TEXTURES = [[핀 스타일]], -- (new Python translation)
  NO_WAYPOINT_TO_CHAT = [[공유할 경유지 없음]],
  TEXTURES = [[텍스처]],
  RIGHT_CLICK_FOR_OPTIONS = [[옵션을 보려면 마우스 오른쪽 버튼을 클릭하세요.]],
  CHAT_WAYPOINT = [[채팅으로 보내기]],
  CTRL_C_COPY = [[Ctrl + C로 강조된 텍스트 복사.]],
  CANNOT_SET_WAYPOINT = [[이 위치에 경유지를 설정할 수 없습니다 (맵 %s, %s).]],
  NO_SAVED_WAYPOINT = [[해당 ID의 저장된 경유지 없음]],
  DELETE_ALL = [[모두 삭제]],
  MORE_OPTIONS = [[(더 많은 옵션 - > %s - > %s - >
 %s - > %s)]],
  LOADED = [[로드됩니다.]],
  CLICK_TO_SAVE = [[이 위치를 컬렉션에 저장하려면 클릭하세요.]],
  WAYPOINTS = [[중간지점]],
}
