
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.ptBR = {
  COULD_NOT_DETERMINE_POSITION = [[Não foi possível determinar a posição atual]],
  NO_WAYPOINTS_MATCH = [[Nenhum ponto de passagem corresponde à sua pesquisa.]],
  CLICK_TO_HIGHLIGHT = [[Clique para destacar]],
  FONT = [[Fonte]],
  NEW_WAYPOINT = [[Novo Waypoint]],
  CANNOT_SET_WAYPOINT = [[Não é possível definir um ponto de passagem para este local (mapa %s, %s).]],
  OVERRIDE_WAYPOINT_BG = [[Escolher textura]],
  SETTINGS_TOMTOM_READY = [[A TomTom está carregada e pronta.]],
  NO_DESCRIPTION = [[Sem descrição]],
  WAYPOINT_IN = [[Waypoint em %s]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[Níveis:
1 - Filiação
2 - Continente
3 - Mundo]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[Clique para ativar este waypoint]],
  MAP_PINS = [[Pinos do mapa]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[Fonte do título]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[Nível padrão do pino do mapa]],
  SLASH_TT2 = [[Cargo Atual]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[Tamanho padrão do pino do mapa]],
  NO_SAVED_WAYPOINTS_YET = [[Ainda não há pontos de passagem salvos.]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[Altura da fonte do título]],
  WAYPOINT_NAME_COLOR = [[Cor do nome do waypoint]],
  FONT_OPTIONS = [[Opções do Tipo de Letra]],
  SETTINGS_TOMTOM_INSTALLED = [[A TomTom está instalada e carregará quando necessário.]],
  DELETE_ALL_SAVED_WAYPOINTS = [[Eliminar todos os pontos de rota guardados na sua coleção]],
  SETTINGS_NAVIGATION_HINT = [[Quando ativado, a TomTom é a preferida. O pino do mapa do jogo é usado de outra forma, inclusive quando a TomTom falha.]],
  SETTINGS_USE_TOMTOM = [[Use a TomTom com %s]],
  CLICK_TO_SAVE = [[Clique para guardar este local na sua coleção]],
  WAYPOINTS = [[Paragens]],
  PROFILE_LOADED = [[Perfil carregado com sucesso]],
  RIGHT_CLICK_FOR_OPTIONS = [[Clique com o botão direito para obter mais opções]],
  COORDINATES = [[Coordenadas]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[Clique para desativar este waypoint]],
  LOADED = [[carregado]],
  DELETE_WAYPOINT_DESC = [[Remover este ponto de passagem da sua coleção.]],
  LEFT_CLICK_TOGGLE = [[Clique esquerdo: Alternar interface]],
  WAYPOINT = [[Ponto de passagem]],
  SLASH_TT1 = [[Abrir/fechar %s]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[Pinos de mapa persistentes]],
  COULD_NOT_PARSE_COORDS = [[Não foi possível processar as coordenadas.]],
  MORE_OPTIONS = [[(mais opções em -> %s -> %s ->
 %s -> %s)]],
  SLASH_COMMANDS = [[Comandos de barra]],
  DELETE_ALL = [[Eliminar tudo]],
  SLASH_TT3 = [[Uso: %s #mapId x y name -d description]],
  TEXTURES = [[Texturas]], -- (new Python translation)
  WAYPOINT_NAME_COLOR_RESET = [[Clique com o botão direito do mouse: redefinir para a cor da fonte padrão.]],
  CHAT_WAYPOINT = [[Enviar para o chat]],
  SETTINGS_TOMTOM_MISSING = [[A TomTom não está instalada.]],
  EDIT_WAYPOINT_DESC = [[Atualizar nome e descrição deste ponto de passagem.]],
  WAYPOINT_VIA_TOMTOM = [[TomTom]],
  NO_SAVED_WAYPOINT = [[Nenhum ponto de passagem salvo com esse ID]],
  SETTINGS_NAVIGATION = [[Navegação; orientação]],
  CONFIRM_DELETE_ALL = [[Tem certeza de que deseja excluir todas as variações? Isto não pode ser desfeito.]],
  CTRL_C_COPY = [[Ctrl + C para copiar o texto destacado.]],
  WAYPOINT_SET_TO = [[Ponto de rota definido para %s]],
  NO_WAYPOINT_TO_CHAT = [[Nenhum ponto de passagem para compartilhar]],
  INVALID_COORDS = [[Coordenadas inválidas: %s (deve estar entre 0-100)]],
}
