
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.ruRU = {
  COULD_NOT_DETERMINE_POSITION = [[Не удалось определить текущее положение]],
  NO_WAYPOINTS_MATCH = [[Нет точек маршрута, соответствующих поиску.]],
  CLICK_TO_HIGHLIGHT = [[Нажмите для выделения]],
  FONT = [[Шрифт]],
  NEW_WAYPOINT = [[Новая путевая точка]],
  CANNOT_SET_WAYPOINT = [[Невозможно установить точку маршрута для этого места (карта %s, %s).]],
  OVERRIDE_WAYPOINT_BG = [[Выберите текстуру]],
  SETTINGS_TOMTOM_READY = [[TomTom загружен и готов.]],
  NO_DESCRIPTION = [[Нет описания]],
  WAYPOINT_IN = [[Путевая точка в %s]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[Уровни:
1 - Родитель
2 - Континент
3 - Мир]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[Нажмите, чтобы активировать эту путевую точку]],
  MAP_PINS = [[Карты контактов]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[Шрифт заголовка]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[Уровень штифта карты по умолчанию]],
  SLASH_TT2 = [[Нынешнее положение]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[Размер булавки карты по умолчанию]],
  NO_SAVED_WAYPOINTS_YET = [[Пока нет сохранённых точек маршрута.]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[Высота шрифта заголовка]],
  WAYPOINT_NAME_COLOR = [[Цвет названия путевой точки]],
  FONT_OPTIONS = [[Настройка шрифтов]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom установлен и будет загружаться при необходимости.]],
  DELETE_ALL_SAVED_WAYPOINTS = [[Удалить все сохраненные путевые точки в коллекции]],
  SETTINGS_NAVIGATION_HINT = [[При включении TomTom является предпочтительным. PIN игровой карты используется иначе, в том числе при сбое TomTom.]],
  SETTINGS_USE_TOMTOM = [[Используйте TomTom с %s]],
  CLICK_TO_SAVE = [[Нажмите, чтобы сохранить это местоположение в коллекции]],
  WAYPOINTS = [[Путевые точки]],
  PROFILE_LOADED = [[Профиль успешно загружен]],
  RIGHT_CLICK_FOR_OPTIONS = [[Щелкните правой кнопкой мыши для получения дополнительных параметров.]],
  COORDINATES = [[Координаты]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[Нажмите, чтобы отключить эту путевую точку]],
  LOADED = [[загружен]],
  DELETE_WAYPOINT_DESC = [[Удалить эту точку маршрута из коллекции.]],
  LEFT_CLICK_TOGGLE = [[ЛКМ: Переключить интерфейс]],
  WAYPOINT = [[Точка маршрута]],
  SLASH_TT1 = [[Открыть/закрыть %s]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[Постоянные булавки карты]],
  COULD_NOT_PARSE_COORDS = [[Не удаётся обработать координаты.]],
  MORE_OPTIONS = [[(больше опций в -> %s -> %s ->
 %s -> %s)]],
  SLASH_COMMANDS = [[Команды косой черты]],
  DELETE_ALL = [[Удалить все]],
  SLASH_TT3 = [[Использование: %s #mapId x y name -d description]],
  TEXTURES = [[Текстуры]], -- (new Python translation)
  WAYPOINT_NAME_COLOR_RESET = [[Щелкните правой кнопкой мыши: сброс к цвету шрифта по умолчанию.]],
  CHAT_WAYPOINT = [[Отправить в чат]],
  SETTINGS_TOMTOM_MISSING = [[TomTom не установлен.]],
  EDIT_WAYPOINT_DESC = [[Обновить название и описание этой точки маршрута.]],
  WAYPOINT_VIA_TOMTOM = [[TomTom]],
  NO_SAVED_WAYPOINT = [[Нет сохранённой точки маршрута с таким ID]],
  SETTINGS_NAVIGATION = [[Навигация]],
  CONFIRM_DELETE_ALL = [[Вы уверены, что хотите удалить все вариации? Эту операцию невозможно отменить.]],
  CTRL_C_COPY = [[Ctrl + C для копирования выделенного текста.]],
  WAYPOINT_SET_TO = [[Путевая точка установлена на %s]],
  NO_WAYPOINT_TO_CHAT = [[Нет точки маршрута для отправки]],
  INVALID_COORDS = [[Недопустимые координаты: %s (должно быть от 0 до 100)]],
}
