
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.zhCN = {
  SLASH_TT3 = [[用法： %s # mapId x y name -d description]],
  SETTINGS_USE_TOMTOM = [[将TomTom与%s一起使用]],
  NO_WAYPOINTS_MATCH = [[没有路径点匹配您的搜索。]],
  COULD_NOT_DETERMINE_POSITION = [[无法确定当前位置]],
  NO_DESCRIPTION = [[无描述]],
  WAYPOINT = [[路径点]],
  COORDINATES = [[坐标]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[等级：
1 -父母
2 -大陆
3 -世界]],
  WAYPOINT_SET_TO = [[路径点已设置为]],
  WAYPOINT_VIA_TOMTOM = [[TomTom]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[单击以停用此航点]],
  FONT = [[字体]],
  INVALID_COORDS = [[无效的坐标： %s （必须在0-100之间）]],
  DELETE_ALL_SAVED_WAYPOINTS = [[删除集合中所有已保存的航点]],
  WAYPOINT_NAME_COLOR = [[航点名称颜色]],
  CLICK_TO_HIGHLIGHT = [[点击以高亮]],
  MAP_PINS = [[地图图钉]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[默认地图图钉级别]],
  DELETE_WAYPOINT_DESC = [[从收藏中移除此路径点。]],
  SETTINGS_NAVIGATION_HINT = [[启用后，首选TomTom。游戏地图图钉以其他方式使用，包括TomTom失败时。]],
  SETTINGS_NAVIGATION = [[导航]],
  NO_SAVED_WAYPOINTS_YET = [[暂无已保存的路径点。]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[单击以激活此路点]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[标题字体高度]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[标题字体]],
  SLASH_TT2 = [[保存现在位置]],
  WAYPOINT_NAME_COLOR_RESET = [[右键单击：重置为默认字体颜色。]],
  FONT_OPTIONS = [[字体设置]],
  CONFIRM_DELETE_ALL = [[您确定要删除所有版本吗？ 这不能被撤消。]],
  SETTINGS_TOMTOM_READY = [[TomTom已加载并准备就绪。]],
  SETTINGS_TOMTOM_MISSING = [[TomTom未安装。]],
  NEW_WAYPOINT = [[新航点]],
  SLASH_TT1 = [[打开/关闭%s]],
  COULD_NOT_PARSE_COORDS = [[无法识别坐标值]],
  PROFILE_LOADED = [[配置文件已成功加载]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom已安装，并将在需要时加载。]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[永久性地图图钉]],
  OVERRIDE_WAYPOINT_BG = [[选择纹理]],
  WAYPOINT_IN = [[路径点在]],
  LEFT_CLICK_TOGGLE = [[左键单击：切换界面]],
  SLASH_COMMANDS = [[斜杠命令]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[默认地图图钉大小]],
  EDIT_WAYPOINT_DESC = [[更新此路径点的名称和描述。]],
  PIN_TEXTURES = [[图钉样式]], -- (new Python translation)
  NO_WAYPOINT_TO_CHAT = [[没有要分享的路径点]],
  TEXTURES = [[纹理]],
  RIGHT_CLICK_FOR_OPTIONS = [[右键单击可查看选项]],
  CHAT_WAYPOINT = [[发送到聊天]],
  CTRL_C_COPY = [[Ctrl + C 复制高亮文本。]],
  CANNOT_SET_WAYPOINT = [[无法为此位置设置路径点（地图 %s，%s）。]],
  NO_SAVED_WAYPOINT = [[没有该ID的已保存路径点]],
  DELETE_ALL = [[Delete all]],
  MORE_OPTIONS = [[（更多选项在- > %s - > %s - >
 %s - > %s)]],
  LOADED = [[载入。]],
  CLICK_TO_SAVE = [[单击以将此位置保存到您的收藏集]],
  WAYPOINTS = [[点]],
}
