
local _, Lodestone = ...
Lodestone.Localization = Lodestone.Localization or {}

Lodestone.Localization.zhTW = {
  COULD_NOT_DETERMINE_POSITION = [[無法確定目前位置]],
  NO_WAYPOINTS_MATCH = [[沒有路徑點符合您的搜尋。]],
  CLICK_TO_HIGHLIGHT = [[點擊以反白]],
  FONT = [[站點標題字體設置]],
  NEW_WAYPOINT = [[新航點]],
  CANNOT_SET_WAYPOINT = [[無法為此位置設置路徑點（地圖 %s，%s）。]],
  OVERRIDE_WAYPOINT_BG = [[選擇紋理]],
  SETTINGS_TOMTOM_READY = [[TomTom已載入並準備就緒。]],
  NO_DESCRIPTION = [[無描述]],
  WAYPOINT_IN = [[%s中的航點]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL_TT = [[等級：
1 -父母
2 -大陸
3 -世界]],
  CLICK_TO_ACTIVATE_WAYPOINT = [[按一下以啟動此路點]],
  MAP_PINS = [[地圖Pins]],
  SETTINGS_WAYPOINT_TITLE_FONT = [[標題字型]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_LEVEL = [[預設地圖圖釘等級]],
  SLASH_TT2 = [[當前封裝]],
  SETTINGS_WAYPOINT_DEFAULT_MAP_PIN_SIZE = [[預設地圖圖釘大小]],
  NO_SAVED_WAYPOINTS_YET = [[目前尚無已儲存的路徑點。]],
  SETTINGS_WAYPOINT_TITLE_FONT_HEIGHT = [[標題字體高度]],
  WAYPOINT_NAME_COLOR = [[航點名稱顏色]],
  FONT_OPTIONS = [[字體選項]],
  SETTINGS_TOMTOM_INSTALLED = [[TomTom已安裝，並將在需要時載入。]],
  DELETE_ALL_SAVED_WAYPOINTS = [[刪除集合中所有已儲存的路點]],
  SETTINGS_NAVIGATION_HINT = [[啟用時，首選TomTom。遊戲地圖圖釘以其他方式使用，包括TomTom失敗時。]],
  SETTINGS_USE_TOMTOM = [[將TomTom與%s一起使用]],
  CLICK_TO_SAVE = [[按一下以將此位置儲存至您的收藏]],
  WAYPOINTS = [[路徑點]],
  PROFILE_LOADED = [[已成功載入個人資料]],
  RIGHT_CLICK_FOR_OPTIONS = [[點擊滑鼠右鍵查看選項]],
  COORDINATES = [[座標]],
  CLICK_TO_DEACTIVATE_WAYPOINT = [[按一下以停用此航點]],
  LOADED = [[已載入]],
  DELETE_WAYPOINT_DESC = [[從收藏中移除此路徑點。]],
  LEFT_CLICK_TOGGLE = [[左鍵點擊：切換介面]],
  WAYPOINT = [[路徑點]],
  SLASH_TT1 = [[開啟/關閉%s]],
  SETTINGS_WAYPOINT_PERISTENT_MAP_PINS = [[永久性地圖圖釘]],
  COULD_NOT_PARSE_COORDS = [[無法解析座標]],
  MORE_OPTIONS = [[（更多選項在- > %s - > %s - >
 %s - > %s ）]],
  SLASH_COMMANDS = [[斜槓命令]],
  DELETE_ALL = [[全部刪除]],
  SLASH_TT3 = [[用法： %s # mapId x y name -d description]],
  TEXTURES = [[材质........................................................................................................]], -- (new Python translation)
  WAYPOINT_NAME_COLOR_RESET = [[鼠標右鍵單擊：重置為默認字體顏色。]],
  CHAT_WAYPOINT = [[傳送至即時對話]],
  SETTINGS_TOMTOM_MISSING = [[未安裝TomTom。]],
  EDIT_WAYPOINT_DESC = [[更新此路徑點的名稱和描述。]],
  WAYPOINT_VIA_TOMTOM = [[(TomTom)]],
  NO_SAVED_WAYPOINT = [[沒有該ID的已儲存路徑點]],
  SETTINGS_NAVIGATION = [[管理面板導航文字]],
  CONFIRM_DELETE_ALL = [[你確定要刪除所有變化類型嗎？這項操作不可復原喔.]],
  CTRL_C_COPY = [[Ctrl + C 複製反白文字。]],
  WAYPOINT_SET_TO = [[路點設定為%s]],
  NO_WAYPOINT_TO_CHAT = [[沒有要分享的路徑點]],
  INVALID_COORDS = [[無效的座標： %s （必須在0-100之間）]],
}
